### ISSUE TITLE
사이드바 서브 menu css 수정 요망

### ISSUE THREAD

**Issue by younhoso** [younhoso/TriplexLab-Blog#20]
12 / 22 다음과 같이 작업 수행 완료!
<img width="290" alt="스크린샷 2022-12-22 오후 11 04 54" src="https://user-images.githubusercontent.com/30254570/209151216-8e825b07-0084-4e9b-bbb9-1ef627ce5335.png">

**Comment by hyunseokSon** [comment]
수정 요청 드린 것 바로 해결해주셔서 장밀 감사드립니다! 
유용하게 쓰겠습니다 :)
