### ISSUE TITLE
티스토리 동영상 첨부 시 안나오는 현상

### ISSUE THREAD

**Issue by seokhunyun** [younhoso/TriplexLab-Blog#30]
안녕하세요.
티스토리에 스킨 적용 후 동영상을 첨부하면 보이지 않는 현상이 있습니다.
확인 부탁드려도 될까요?

**Comment by younhoso** [comment]
동영상을 첨부하셨다고하는데... 어디에 어떻게 첨부를 하셨는지 자세히 설명 부탁드립니다.

**Comment by younhoso** [comment]
> 안녕하세요. 티스토리에 피부 적용 후 동영상을 부착하면 보이지 않는 폐색이 있습니다. 확인 부탁해도 될까요?

동영상을 첨부했다면 어디에서나... 어떻게 첨부했는지 자세히 설명 부탁드립니다.

**Comment by seokhunyun** [comment]
> > 안녕하세요. 티스토리에 피부 적용 후 동영상을 부착하면 보이지 않는 폐색이 있습니다. 확인 부탁해도 될까요?
> 
> 동영상을 첨부했다면 어디에, 어떻게 첨부했는지 자세히 설명 부탁드립니다.

안녕하세요.
티스토리 글쓰기에서 동영상 첨부 기능으로 첨부했습니다.
브라우저도 바꿔보고 동영상 크기도 변경해봤는데 글 게시 후에는 보이질 않습니다.

![image](https://user-images.githubusercontent.com/63761519/231616172-5039e7b6-f5d9-4cda-9b85-1997f266faea.png)

감사합니다.

**Comment by younhoso** [comment]
> > > 안녕하세요. 티스토리에 피부 적용 후 동영상을 부착하면 보이지 않는 폐색이 있습니다. 확인 부탁해도 될까요?
> > 
> > 
> > 동영상을 첨부했다면 어디에, 어떻게 첨부했는지 자세히 설명 부탁드립니다.
> 
> 안녕하세요. 티스토리 글쓰기에서 동영상 첨부 기능으로 첨부했습니다. 브라우저도 바꿔보고 동영상 크기도 변경해봤는데 글 게시 후에는 보이질 않습니다.
> 
> ![image](https://user-images.githubusercontent.com/63761519/231616172-5039e7b6-f5d9-4cda-9b85-1997f266faea.png)
> 
> 감사합니다.

해당 부분 수정해서 반영했습니다.
https://github.com/younhoso/TriplexLab-Blog/commit/2d0df4b663edab461ef7c3ca083544bde6e4c6b9
확인 해보시고, 다시 다운로드 받아서 업로드 해보세요~
제가 확인 했을때는 잘 되었는데, 만약 해보시고 그래도 이상 있으면 댓글 남겨주세요~

**Comment by seokhunyun** [comment]
감사합니다. 확인해보겠습니다.
