### ISSUE TITLE
코드 영역에 있는 코드에 InputMono 글씨체가 적용이 안됩니다.

### ISSUE THREAD

**Issue by minmoong** [younhoso/TriplexLab-Blog#31]
안녕하세요. TriplexLab 스킨 테마를 오늘 처음 사용하네요 ㅎㅎ 이쁩니다.

그런데 코드 블럭 안에 있는 JavaScript 코드에 InputMono 글씨체가 적용이 안돼있네요.
티스토리 기본 코드 하일라이팅 플러그인은 해제한 상태입니다.

![캡처](https://github.com/younhoso/TriplexLab-Blog/assets/62737839/ce72c5f7-b85d-4453-8c42-c87a3802860c)

아래와 같은 글씨체를 적용하려면 어떻게 해야되나요?
![캡처3](https://github.com/younhoso/TriplexLab-Blog/assets/62737839/b3af41d6-2258-4b07-8ea5-7e77207086a3)

**Comment by minmoong** [comment]
![캡처4](https://github.com/younhoso/TriplexLab-Blog/assets/62737839/d3cab200-e95b-42d1-ba68-f301343e65c9)

다크 모드 사용시에도 텍스트 영역의 backgroud-color가 하얀색이네요.. 혹시 바꿀 수 있는 방법이 있을까요?

**Comment by minmoong** [comment]
![캡처1](https://github.com/younhoso/TriplexLab-Blog/assets/62737839/495c221a-69a7-4b7a-95bd-73c9842e2ace)

개발자 도구에서 InputMono 폰트를 해제하니 적용이 됩니다. 폰트끼리 뭔가 충돌이 있는 것 같습니다.

**Comment by younhoso** [comment]
정확한 디버깅을 위해서 블로그 주소도 같이 보내주시면 확인이 더 빠릅니다.
님 블로그 주소도 같이 보내주시면 다시 확인 해보겠습니다.

**Comment by minmoong** [comment]
https://hackssert.tistory.com 입니다

**Comment by younhoso** [comment]
님의 블로그님 지금 폰트가 적용이 안되고 있습니다. 에러부터 해결하면 됩니다.

**Comment by minmoong** [comment]
![캡처](https://github.com/younhoso/TriplexLab-Blog/assets/62737839/144debdb-90b5-490d-bd67-96b9ee734242)

아하 이 에러때문에 폰트가 안가져와졌군요..!!

혹시 cors 에러인데 이거는 티스토리 서버쪽에서 해결해줘야되는거 아닌가여?? 아니면 블로그 설정에서 해결할 수 있는건가요?

**Comment by younhoso** [comment]
해당 부분 수정하여 다시 push 했습니다. 다시 다운로드 받아서 적용해보세요.
