### ISSUE TITLE
글 하단에 prev와 next 순서가 이상합니다.

### ISSUE THREAD

**Issue by minmoong** [younhoso/TriplexLab-Blog#33]
![캡처](https://github.com/younhoso/TriplexLab-Blog/assets/62737839/4ec808ce-331f-47c7-9203-2aa5080507ec)
위와 같이 오른쪽 환경 구축 글부터 왼쪽으로 순서대로 글을 올렸습니다.

![캡처1](https://github.com/younhoso/TriplexLab-Blog/assets/62737839/ee4ae2e6-77e8-4d03-b68c-9bc82e04d63a)
그런데 맨 처음 올린 글인 환경 구축 글의 최하단에 prev(previous) 버튼에 더 나중에 올린 게시물이 링크돼있네요.

순서가 이상한 것 같습니다. 어떻게 바꿔야 하나요?

**Comment by minmoong** [comment]
![캡처3](https://github.com/younhoso/TriplexLab-Blog/assets/62737839/56e17d92-2ff0-4e0b-87cc-9b6829c553d3)

skin.html에 prev와 next가 섞여있네요..

**Comment by younhoso** [comment]
순서가 이상한것 같다라는게 무슨 생각을 가지고 댓글을 작성하신 건가요??
님이 올린 글 기준으로 "환경 구축"글 기준으로 prev와 next가 있는것 입니다.

**Comment by minmoong** [comment]
환경 구축 -> 기본 명령어 -> 문제풀이 순으로 블로그 글을 올렸는데 환경 구축 블로그에 들어가서 하단에 보면 next에 기본 명령어 글이 있어야지요. 그런데 제가 블로그 글을 올린 순서와 반대로 돼있다는 얘깁니다

**Comment by minmoong** [comment]
알겠습니다 ❤️

**Comment by younhoso** [comment]
네 정답은 없습니다. 서비스를 만든 사람 마음이지요.~
