### ISSUE TITLE
선생님 죄송한데 혹시 사이드바에 카테고리 접을 수 있게 수정해주실 수 있으신가요....?

### ISSUE THREAD

**Issue by BvrPark** [younhoso/TriplexLab-Blog#34]
사이드바에 카테고리를 접고 싶은데 아무리 수정해봐도 잘 안되서요...부탁드립니다..

**Comment by younhoso** [comment]
해당 기능 같은 경우에는 제가 수정을 하게 되면 특정 개인 스킨에만 적용은 불가하고 
저의 스킨에 버전 업그레이드 해서 해당 기능을 추가하겠습니다. 
정확한 날짜를 픽스는 못정하고 업그레이드 하면 추가 하겠습니다.😀

**Comment by younhoso** [comment]
> 사이드바에 카테고리를 접고 싶은데 아무리 수정해봐도 잘 안되서요...부탁드립니다..

해당 기능 같은 경우에는 제가 수정을 하게 되면 특정 개인 스킨에만 적용은 불가하고
저의 스킨에 버전 업그레이드 해서 해당 기능을 추가하겠습니다.
정확한 날짜를 픽스는 못정하고 업그레이드 하면 추가 하겠습니다.😀
