### ISSUE TITLE
문서 내 하이퍼링크 오류

### ISSUE THREAD

**Issue by jinh9015** [younhoso/TriplexLab-Blog#36]
아래의 html을 사용해 티스토리 문서 내 하이퍼링크 목차 기능을 사용하고자 했는데 트리플엑스랩 테마 적용시 html이 정상적으로 동작하지 않습니다. 혹시 충돌이 발생하는 부분이 있는걸까요?

`<p data-ke-size="size16">목차</p>
<p data-ke-size="size16"><a href="#no0">대제목</a></p>
<p data-ke-size="size16"><a href="#no1">중제목1</a></p>
<p data-ke-size="size16"><a href="#no2">중제목2</a></p>
<p data-ke-size="size16"><a href="#no3">중제목3</a></p>
<p data-ke-size="size16">&nbsp;</p>
<h2 id="no0" data-ke-size="size26"><b>대제목</b></h2>
<p data-ke-size="size16">본문내용 삽입</p>
<p data-ke-size="size16">&nbsp;</p>
<p data-ke-size="size16">&nbsp;</p>
<h3 id="no1" data-ke-size="size23"><b>중제목 1</b></h3>
<p data-ke-size="size16">본문내용 삽입</p>
<p data-ke-size="size16">&nbsp;</p>
<p data-ke-size="size16">&nbsp;</p>
<h3 id="no2" data-ke-size="size23"><b>중제목 2</b></h3>
<p data-ke-size="size16">본문내용 삽입</p>
<p data-ke-size="size16">&nbsp;</p>
<p data-ke-size="size16">&nbsp;</p>
<h3 id="no3" data-ke-size="size23"><b>중제목 3</b></h3>
<p data-ke-size="size16">본문내용 삽입</p>
<p data-ke-size="size16">&nbsp;</p>
<p data-ke-size="size16">&nbsp;</p>`

**Comment by jinh9015** [comment]
정확하게는 화면 옆의 contents란에서 하이퍼링크가 동작하고 본문에서는 동작하지 않습니다.
![Uploading image.png…]()

**Comment by younhoso** [comment]
> 센서는 옆의 콘텐츠란에서 하이퍼링크가 동작하고 본체에서는 동작하지 않습니다. ![영상](https://private-user-images.githubusercontent.com/125936456/292118249-2eae61ee-96f9-453f-b42b-7d2440f32b9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzMzkyMzYsIm5iZiI6MTcwMzMzODkzNiwicGF0aCI6Ii8xMjU5MzY0NTYvMjkyMTE4MjQ5LTJlYWU2MWVlLTk2ZjktNDUzZi1iNDJiLTdkMjQ0MGYzMmI5ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyM1QxMzQyMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iM2QzMDYyODk5YWIxYTI0OTBmNjlmNjUxNjVkNGEzNjlkMmNjODE1MmFlMDFmMDBmNWE0NTIxM2E1OTU2NjJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.o0v4quAwFoHOyR4pVvf8KyLdhrwETFXUcn92dkIW6eY)
> 
> 문제는 표시에 따라 저 오른쪽 내용은 제외됩니다.

아 해당 부분은 추후에 다시 수정하겠습니다. 감사합니다.!

**Comment by younhoso** [comment]
해당 부분은 다른 오류때문에 그런것 같습니다. 콘솔창을 확인해서 오류가 나는것이 있는지 확인 부탁 드립니다.
그리고 "해상도에 따라 저 우측 contents란은 나타나지 않습니다."라고 하셨는데 이건 velog도 마친가지 입니다.(문제가 아니라 정상입니다.😃)
